# version: "3.0"  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:

    producer:  # 定義一個服務，名稱為 producer
        image: shydatas/data_ingestion:latest  # 使用的映像檔名稱與標籤（版本）
        container_name: "scraper_producer"  # 設定 container_name = crawler_hahow_producer
        command: uv run python data_ingestion/message_queue/producer.py
        # restart: always  # 若容器停止或崩潰，自動重新啟動
        environment:
            - TZ=Asia/Taipei  # 設定時區為台北（UTC+8）
            - RABBITMQ_HOST=rabbitmq
        networks:
            - njr20202_network  # 將此服務連接到 my_network 網路

networks:
    njr20202_network:
        external: true
